/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.NopDonXinNghi.newBtnG;
import static GUI.TrangChuSinhVien.LOGO;
import ObjectPG.DonXinNghi;
import ObjectPG.DonXinNghiSV;
import ObjectPG.TableDonXinNghiSV;
import ObjectPG.TableDonXinNghiSVSort;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author trqhu
 */
public class DonXinNghiSort extends javax.swing.JFrame {
    private String maSV;
    static ButtonGroup newBtnG = new ButtonGroup();
    int dongchon = -1;
    DonXinNghiSV dxn = new DonXinNghiSV();
    ArrayList<DonXinNghiSV> arrayListDXN;

    /**
     * Creates new form DonXinNghiSort
     */
    public DonXinNghiSort() {
        
        initComponents();
        newBtnG.add(rdBinhThuong);
        newBtnG.add(rdBiBenh);
        formatHeader();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        DonXinNghiSV.readData();
        arrayListDXN = new ArrayList<DonXinNghiSV>(DonXinNghiSV.dxnsvs);

    }
    
    public DonXinNghiSort(String maSV) {
        this.maSV = maSV;
        ArrayList<DonXinNghiSV> temp = new ArrayList<>();
        initComponents();
        newBtnG.add(rdBinhThuong);
        newBtnG.add(rdBiBenh);
        formatHeader();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        DonXinNghiSV.readData();
        arrayListDXN = new ArrayList<DonXinNghiSV>(DonXinNghiSV.dxnsvs);
        LoadTableDXN(temp);
    }

    public void showLogo(String linkImage) {
        try {
            BufferedImage img = null;
            img = ImageIO.read(new File(linkImage));
            Image img1 = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(img1));
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void formatHeader() {
        showLogo(LOGO);
        tNameUniversity.setText("Trường Đại Học Công Nghiệp Hà Nội");
        tName.setText("Ðơn xin nghỉ");
    }

    public void LoadTableDXN(ArrayList<DonXinNghiSV> a) {
        for(DonXinNghiSV temp : arrayListDXN) {
            if(temp.getMaSV().equals(maSV))
                a.add(temp);
        }
        tableDXN.setModel(new TableDonXinNghiSVSort(a));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tNameUniversity = new javax.swing.JLabel();
        tName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDXN = new javax.swing.JTable();
        jTitle = new javax.swing.JLabel();
        tMaDon = new javax.swing.JLabel();
        tMaSV = new javax.swing.JLabel();
        tMaSV1 = new javax.swing.JLabel();
        tMaSV2 = new javax.swing.JLabel();
        tMaSV3 = new javax.swing.JLabel();
        tMaSV4 = new javax.swing.JLabel();
        tMaSV5 = new javax.swing.JLabel();
        tMaSV6 = new javax.swing.JLabel();
        tfMaDon = new javax.swing.JTextField();
        tfMaSV = new javax.swing.JTextField();
        tfLyDo = new javax.swing.JTextField();
        tfNgayNop = new javax.swing.JTextField();
        tfNgayBDN = new javax.swing.JTextField();
        tfNgayKTN = new javax.swing.JTextField();
        displayImage = new javax.swing.JLabel();
        tfLink = new javax.swing.JTextField();
        rdBinhThuong = new javax.swing.JRadioButton();
        rdBiBenh = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 800));

        jLabel1.setText("Logo");

        tNameUniversity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNameUniversity.setText("Name University");

        tName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tName.setText("Name");

        tableDXN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDXNMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableDXN);

        jTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTitle.setForeground(new java.awt.Color(102, 51, 0));
        jTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitle.setText("Danh sách đơn đã nộp");

        tMaDon.setText("Mã đơn:");

        tMaSV.setText("Mã sinh viên:");

        tMaSV1.setText("Lý do:");

        tMaSV2.setText("Ảnh:");

        tMaSV3.setText("Tình trạng sức khỏe:");

        tMaSV4.setText("Ngày nộp:");

        tMaSV5.setText("Ngày bắt đầu nghỉ:");

        tMaSV6.setText("Ngày kết thúc nghỉ:");

        tfMaDon.setEnabled(false);

        tfMaSV.setEnabled(false);

        tfLyDo.setEnabled(false);

        tfNgayNop.setEnabled(false);

        tfNgayBDN.setForeground(new java.awt.Color(153, 153, 153));
        tfNgayBDN.setEnabled(false);
        tfNgayBDN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNgayBDNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNgayBDNFocusLost(evt);
            }
        });

        tfNgayKTN.setForeground(new java.awt.Color(153, 153, 153));
        tfNgayKTN.setEnabled(false);
        tfNgayKTN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNgayKTNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNgayKTNFocusLost(evt);
            }
        });

        displayImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tfLink.setEnabled(false);
        tfLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLinkActionPerformed(evt);
            }
        });

        rdBinhThuong.setText("Bình thường");
        rdBinhThuong.setEnabled(false);

        rdBiBenh.setText("Bị bệnh");
        rdBiBenh.setEnabled(false);

        jButton1.setText("Theo Mã Đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Theo Mã SV");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Theo ngày nộp");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sắp xếp");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton4.setText("Theo TTSK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tMaSV2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tMaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tMaSV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tMaSV3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tMaSV4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tMaSV5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tMaSV6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfMaDon)
                                .addComponent(tfMaSV)
                                .addComponent(tfLyDo)
                                .addComponent(tfNgayNop)
                                .addComponent(tfNgayBDN)
                                .addComponent(tfNgayKTN)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(displayImage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfLink, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdBinhThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(rdBiBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNameUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNameUniversity)
                    .addComponent(tName))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMaDon)
                    .addComponent(tfMaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMaSV)
                    .addComponent(tfMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMaSV1)
                    .addComponent(tfLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMaSV3)
                    .addComponent(rdBinhThuong)
                    .addComponent(rdBiBenh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMaSV4)
                    .addComponent(tfNgayNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMaSV5)
                    .addComponent(tfNgayBDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMaSV6)
                    .addComponent(tfNgayKTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfLink, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tMaSV2)
                        .addComponent(displayImage, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableDXNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDXNMouseClicked
        // TODO add your handling code here:
        dongchon = tableDXN.getSelectedRow();
        if (dongchon != -1) {
            ArrayList<DonXinNghiSV> newDxns = new ArrayList<DonXinNghiSV>(DonXinNghiSV.dxnsvs);
            dxn = newDxns.get(dongchon);
            tfMaDon.setText(dxn.getMaDon() + "");
            tfMaSV.setText(dxn.getMaSV() + "");
            tfLyDo.setText(dxn.getLyDo());
            if (dxn.gettTSK().compareTo("Bình thường") == 0) {
                rdBinhThuong.setSelected(true);
            }
            if (dxn.gettTSK().compareTo("Bị bệnh") == 0) {
                rdBiBenh.setSelected(true);
            }
            tfNgayNop.setText(dxn.getNgayNop());
            tfNgayBDN.setText(dxn.getNgayBatDauNghi());
            tfNgayKTN.setText(dxn.getNgayKetThucNghi());
            tfLink.setText(dxn.getAnh());

            String subLink = dxn.getAnh().substring(dxn.getAnh().lastIndexOf("\\") + 1);

            try {
                BufferedImage img = null;
                img = ImageIO.read(new File("./src/File/Image/DonXinNghi/" + subLink));
                Image img1 = img.getScaledInstance(displayImage.getWidth(), displayImage.getHeight(), Image.SCALE_SMOOTH);
                displayImage.setIcon(new ImageIcon(img1));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.toString());
            }
        }
    }//GEN-LAST:event_tableDXNMouseClicked

    private void tfNgayBDNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNgayBDNFocusGained
        // TODO add your handling code here:
        if (tfNgayBDN.getText().equals("yyyy-mm-dd")) {
            tfNgayBDN.setText("");
            tfNgayBDN.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfNgayBDNFocusGained

    private void tfNgayBDNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNgayBDNFocusLost
        // TODO add your handling code here:
        if (tfNgayBDN.getText().equals("")) {
            tfNgayBDN.setText("yyyy-mm-dd");
            tfNgayBDN.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfNgayBDNFocusLost

    private void tfNgayKTNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNgayKTNFocusGained
        // TODO add your handling code here:
        if (tfNgayKTN.getText().equals("yyyy-mm-dd")) {
            tfNgayKTN.setText("");
            tfNgayKTN.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfNgayKTNFocusGained

    private void tfNgayKTNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNgayKTNFocusLost
        // TODO add your handling code here:
        if (tfNgayKTN.getText().equals("")) {
            tfNgayKTN.setText("yyyy-mm-dd");
            tfNgayKTN.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfNgayKTNFocusLost

    private void tfLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLinkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<DonXinNghiSV> temp = new ArrayList<DonXinNghiSV>();
        jTitle.setText("Đơn đã nộp sắp xếp theo mã đơn");
        Comparator<DonXinNghiSV> c = new Comparator<DonXinNghiSV>() {
            @Override
            public int compare(DonXinNghiSV o1, DonXinNghiSV o2) {
                return o1.getMaDon().compareTo(o2.getMaDon());
            }
        };
        
        Collections.sort(arrayListDXN, c);
        LoadTableDXN(temp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ArrayList<DonXinNghiSV> temp = new ArrayList<DonXinNghiSV>();
        jTitle.setText("Đơn đã nộp sắp xếp theo mã sinh viên");
        Comparator<DonXinNghiSV> c = new Comparator<DonXinNghiSV>() {
            @Override
            public int compare(DonXinNghiSV o1, DonXinNghiSV o2) {
                return o1.getMaSV().compareTo(o2.getMaSV());
            }
        };
        
        Collections.sort(arrayListDXN, c);
        LoadTableDXN(temp);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ArrayList<DonXinNghiSV> temp = new ArrayList<DonXinNghiSV>();
        jTitle.setText("Đơn đã nộp sắp xếp theo ngày nộp");
        Comparator<DonXinNghiSV> c = new Comparator<DonXinNghiSV>() {
            @Override
            public int compare(DonXinNghiSV o1, DonXinNghiSV o2) {
                return o1.getNgayNop().compareTo(o2.getNgayNop());
            }
        };
        
        Collections.sort(arrayListDXN, c);
        LoadTableDXN(temp);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ArrayList<DonXinNghiSV> temp = new ArrayList<DonXinNghiSV>();
        jTitle.setText("Đơn đã nộp sắp xếp theo TTSK");
        Comparator<DonXinNghiSV> c = new Comparator<DonXinNghiSV>() {
            @Override
            public int compare(DonXinNghiSV o1, DonXinNghiSV o2) {
                return o1.gettTSK().compareTo(o2.gettTSK());
            }
        };
        
        Collections.sort(arrayListDXN, c);
        LoadTableDXN(temp);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jTitle;
    private javax.swing.JRadioButton rdBiBenh;
    private javax.swing.JRadioButton rdBinhThuong;
    private javax.swing.JLabel tMaDon;
    private javax.swing.JLabel tMaSV;
    private javax.swing.JLabel tMaSV1;
    private javax.swing.JLabel tMaSV2;
    private javax.swing.JLabel tMaSV3;
    private javax.swing.JLabel tMaSV4;
    private javax.swing.JLabel tMaSV5;
    private javax.swing.JLabel tMaSV6;
    private javax.swing.JLabel tName;
    private javax.swing.JLabel tNameUniversity;
    private javax.swing.JTable tableDXN;
    private javax.swing.JTextField tfLink;
    private javax.swing.JTextField tfLyDo;
    private javax.swing.JTextField tfMaDon;
    private javax.swing.JTextField tfMaSV;
    private javax.swing.JTextField tfNgayBDN;
    private javax.swing.JTextField tfNgayKTN;
    private javax.swing.JTextField tfNgayNop;
    // End of variables declaration//GEN-END:variables
}
