/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.TrangChuGiaoVien.LOGO;
import ObjectPG.KhaiBaoYTeGiaoVien;
import ObjectPG.TableKhaiBaoYTe;
import ObjectPG.TableKhaiBaoYTeGV;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.TreeSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HQuan
 */
public class KhaiBaoYTeGV extends javax.swing.JFrame {

    private String maGV;
    int dongchon = -1;
    KhaiBaoYTeGiaoVien kbyt = new KhaiBaoYTeGiaoVien();
    static TreeSet<KhaiBaoYTeGiaoVien> dsDonKhaiBaoTheoMaGV = new TreeSet<>();

    /**
     * Creates new form KhaiBaoYTe
     */
    public void LoadTableKBYT() {
        for (KhaiBaoYTeGiaoVien item : KhaiBaoYTeGiaoVien.kbytgvs) {
            if (item.getMaGV() != null && item.getMaGV().compareTo(maGV) == 0) {
                dsDonKhaiBaoTheoMaGV.add(item);
            }
        }
        tableKBYT.setModel(new TableKhaiBaoYTeGV(dsDonKhaiBaoTheoMaGV));
        //tableKBYT.setModel(new TableKhaiBaoYTe(gv));
    }

    public KhaiBaoYTeGV() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        formatHeader();
        start("");
        KhaiBaoYTeGiaoVien.readData();
        LoadTableKBYT();
    }

    public KhaiBaoYTeGV(String maGV) {
//        txtLyDo.setEnabled(true);
        this.maGV = maGV;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        formatHeader();
        start(maGV);

        KhaiBaoYTeGiaoVien.readData();
        LoadTableKBYT();
    }

    public void showLogo(String linkImage) {
        try {
            BufferedImage img = null;
            img = ImageIO.read(new File(linkImage));
            Image img1 = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(img1));
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void formatHeader() {
        showLogo(LOGO);
        tNameUniversity.setText("Trường Đại Học Công Nghiệp Hà Nội");
        tName.setText("Khai báo y tế");
    }


    public void start(String maGV) {
        LocalDateTime maDon = LocalDateTime.now();
        txtMaDon.setText(maDon.toString());
        txtMaGV.setText(maGV);
        LocalDate today = LocalDate.now();
        txtNgayNop.setText(today.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tNameUniversity = new javax.swing.JLabel();
        tName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableKBYT = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnNewDon = new javax.swing.JButton();
        btnSuaDon = new javax.swing.JButton();
        tMaDon = new javax.swing.JLabel();
        tMaGV = new javax.swing.JLabel();
        labelKhac = new javax.swing.JLabel();
        labelTrieuChung = new javax.swing.JLabel();
        labelThuocDien = new javax.swing.JLabel();
        labelNgayNop = new javax.swing.JLabel();
        txtMaDon = new javax.swing.JTextField();
        txtMaGV = new javax.swing.JTextField();
        txtKhac = new javax.swing.JTextField();
        txtNgayNop = new javax.swing.JTextField();
        rdF0 = new javax.swing.JRadioButton();
        rdF1 = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        rdKhac = new javax.swing.JRadioButton();
        cbSot = new javax.swing.JCheckBox();
        cbHo = new javax.swing.JCheckBox();
        cbMM = new javax.swing.JCheckBox();
        cbKhoTho = new javax.swing.JCheckBox();
        cbDauDau = new javax.swing.JCheckBox();
        cbMVG = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 800));

        jLabel1.setText("Logo");

        tNameUniversity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNameUniversity.setText("Name University");

        tName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tName.setText("Name");

        tableKBYT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKBYTMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableKBYT);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Biểu mẫu đã khai báo");

        btnNewDon.setText("Nộp đơn mới");
        btnNewDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDonActionPerformed(evt);
            }
        });

        btnSuaDon.setText("Sửa đơn");
        btnSuaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDonActionPerformed(evt);
            }
        });

        tMaDon.setText("Mã khai báo:");

        tMaGV.setText("Mã giáo viên:");

        labelKhac.setText("Nói rõ:");

        labelTrieuChung.setText("Triệu chứng:");

        labelThuocDien.setText("Thuộc diện:");

        labelNgayNop.setText("Ngày nộp:");

        txtMaDon.setEnabled(false);

        txtMaGV.setEnabled(false);

        txtKhac.setEnabled(false);

        txtNgayNop.setEnabled(false);

        buttonGroup1.add(rdF0);
        rdF0.setText("F0");
        rdF0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdF0ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdF1);
        rdF1.setText("F1");
        rdF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdF1ActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdKhac);
        rdKhac.setText("Khác");
        rdKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdKhacActionPerformed(evt);
            }
        });

        cbSot.setText("Sốt");

        cbHo.setText("Ho");

        cbMM.setText("Mệt, mỏi");

        cbKhoTho.setText("Khó thở");

        cbDauDau.setText("Đau đầu");

        cbMVG.setText("Mất vị giác");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(btnClear))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane3)))
                .addGap(95, 95, 95))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelTrieuChung, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbSot, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbKhoTho, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(83, 83, 83)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbMVG, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbHo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(73, 73, 73)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbMM, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbDauDau, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNgayNop)
                                            .addComponent(labelKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtKhac, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                                            .addComponent(txtNgayNop))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tMaGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelThuocDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tMaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rdF0, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                        .addComponent(rdF1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(rdKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 487, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNameUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnNewDon)
                        .addGap(180, 180, 180)
                        .addComponent(btnSuaDon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNameUniversity)
                    .addComponent(tName))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMaDon)
                    .addComponent(txtMaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMaGV)
                    .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelThuocDien)
                    .addComponent(rdF0)
                    .addComponent(rdF1)
                    .addComponent(rdKhac))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKhac)
                    .addComponent(txtKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNgayNop)
                    .addComponent(txtNgayNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTrieuChung)
                    .addComponent(cbSot)
                    .addComponent(cbHo)
                    .addComponent(cbMM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDauDau)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbKhoTho)
                        .addComponent(cbMVG)))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewDon)
                    .addComponent(btnSuaDon))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableKBYTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKBYTMouseClicked
        // TODO add your handling code here:
        dongchon = tableKBYT.getSelectedRow();
        if (dongchon != -1) {
            ArrayList<KhaiBaoYTeGiaoVien> newKbyts = new ArrayList<KhaiBaoYTeGiaoVien>(dsDonKhaiBaoTheoMaGV);
            kbyt = newKbyts.get(dongchon);
            txtMaDon.setText(kbyt.getMaKB());
            txtMaGV.setText(kbyt.getMaGV());
            txtKhac.setText(kbyt.getLyDo());
            txtNgayNop.setText(kbyt.getNgayNop());
            if (kbyt.getThuocDien().compareTo("F0") == 0) {
                rdF0.setSelected(true);
            }
            if (kbyt.getThuocDien().compareTo("F1") == 0) {
                rdF1.setSelected(true);
            }
            if (kbyt.getThuocDien().compareTo("Khác") == 0) {
                rdKhac.setSelected(true);
            }
            String tempTrieuChung = kbyt.getTrangThai();
            String[] trieuChung = tempTrieuChung.split(", ");
            for (String val : trieuChung) {
                if (val.compareTo("Sốt") == 0) {
                    cbSot.setSelected(true);
                }
                if (val.compareTo("Ho") == 0) {
                    cbHo.setSelected(true);
                }
                if (val.compareTo("Mệt,mỏi") == 0) {
                    cbMM.setSelected(true);
                }
                if (val.compareTo("Khó thở") == 0) {
                    cbKhoTho.setSelected(true);
                }
                if (val.compareTo("Mất vị giác") == 0) {
                    cbMVG.setSelected(true);
                }
                if (val.compareTo("Đau đầu") == 0) {
                    cbDauDau.setSelected(true);
                }
            }
        }

    }//GEN-LAST:event_tableKBYTMouseClicked

    public Boolean checkInput() {
        if (txtKhac.getText().compareTo("") == 0 && rdKhac.isSelected()) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
            txtKhac.requestFocus();
            return false;
        } else 
        if (rdF0.isSelected() == false && rdF1.isSelected() == false && rdKhac.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Bạn thuộc đối tượng nào?");
            return false;
        }
        return true;
    }
    private void btnNewDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDonActionPerformed
        if (checkInput()) {
            String thuocDien = "";
            if (rdF0.isSelected()) {
                thuocDien = "F0";
                txtKhac.setText("");
            }
            if (rdF1.isSelected()) {
                thuocDien = "F1";
                txtKhac.setText("");
            }
            if (rdKhac.isSelected()) {
                thuocDien = "Khác";
            }
            String trieuChung = "";
            if (cbSot.isSelected()) {
                trieuChung += "Sốt";
            }
            if (cbHo.isSelected()) {
                trieuChung += ", Ho";
            }
            if (cbMM.isSelected()) {
                trieuChung += ", Mệt,mỏi";
            }
            if (cbKhoTho.isSelected()) {
                trieuChung += ", Khó thở";
            }
            if (cbMVG.isSelected()) {
                trieuChung += ", Mất vị giác";
            }
            if (cbDauDau.isSelected()) {
                trieuChung += ", Đau đầu";
            }
            kbyt = new KhaiBaoYTeGiaoVien(txtMaDon.getText(), txtMaGV.getText(),
                    txtKhac.getText(), txtNgayNop.getText(),
                    thuocDien, trieuChung);

            try {
                KhaiBaoYTeGiaoVien.kbytgvs.add(kbyt);
                JOptionPane.showMessageDialog(this, "Thêm thành công", "Xác nhận", WIDTH);
                LoadTableKBYT();
                KhaiBaoYTeGiaoVien.writeData();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Thêm mới KHÔNG thành công!", "Thông báo", WIDTH);
            }
        }

    }//GEN-LAST:event_btnNewDonActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        start(maGV);
        cbHo.setSelected(false);
        cbDauDau.setSelected(false);
        cbKhoTho.setSelected(false);
        cbMM.setSelected(false);
        cbMVG.setSelected(false);
        cbSot.setSelected(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSuaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDonActionPerformed
        dongchon = tableKBYT.getSelectedRow();
        if (dongchon != -1) {
            ArrayList<KhaiBaoYTeGiaoVien> newKbyts = new ArrayList<KhaiBaoYTeGiaoVien>(dsDonKhaiBaoTheoMaGV);

            if (checkInput()) {
                String thuocDien = "";
                if (rdF0.isSelected()) {
                    thuocDien = "F0";
                    txtKhac.setText("");
                }
                if (rdF1.isSelected()) {
                    thuocDien = "F1";
                    txtKhac.setText("");
                }
                if (rdKhac.isSelected()) {
                    thuocDien = "Khác";
                }
                String trieuChung = "";
                if (cbSot.isSelected()) {
                    trieuChung += "Sốt";
                }
                if (cbHo.isSelected()) {
                    trieuChung += ", Ho";
                }
                if (cbMM.isSelected()) {
                    trieuChung += ", Mệt,mỏi";
                }
                if (cbKhoTho.isSelected()) {
                    trieuChung += ", Khó thở";
                }
                if (cbMVG.isSelected()) {
                    trieuChung += ", Mất vị giác";
                }
                if (cbDauDau.isSelected()) {
                    trieuChung += ", Đau đầu";
                }
                kbyt = new KhaiBaoYTeGiaoVien(txtMaDon.getText(), txtMaGV.getText(),
                        txtKhac.getText(), txtNgayNop.getText(),
                        thuocDien, trieuChung);

                try {
                    newKbyts.set(dongchon, kbyt);
                    KhaiBaoYTeGiaoVien.kbytgvs.remove(newKbyts.get(dongchon));
                    KhaiBaoYTeGiaoVien.kbytgvs.add(kbyt);
                    dsDonKhaiBaoTheoMaGV = new TreeSet<>(newKbyts);
                    JOptionPane.showMessageDialog(this, "Sửa thành công", "Xác nhận", WIDTH);
                    LoadTableKBYT();
                    KhaiBaoYTeGiaoVien.writeData();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Có lỗi", "Thông báo", WIDTH);
                }

            }
        }
    }//GEN-LAST:event_btnSuaDonActionPerformed

    private void rdKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdKhacActionPerformed
        if (rdKhac.isSelected()) {
            txtKhac.setEnabled(true);
            txtKhac.requestFocus();
        }
    }//GEN-LAST:event_rdKhacActionPerformed

    private void rdF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdF1ActionPerformed
        if (rdF1.isSelected()) {
            txtKhac.setEnabled(false);
        }

    }//GEN-LAST:event_rdF1ActionPerformed

    private void rdF0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdF0ActionPerformed
        if (rdF0.isSelected()) {
            txtKhac.setEnabled(false);
        }
    }//GEN-LAST:event_rdF0ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnNewDon;
    private javax.swing.JButton btnSuaDon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbDauDau;
    private javax.swing.JCheckBox cbHo;
    private javax.swing.JCheckBox cbKhoTho;
    private javax.swing.JCheckBox cbMM;
    private javax.swing.JCheckBox cbMVG;
    private javax.swing.JCheckBox cbSot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelKhac;
    private javax.swing.JLabel labelNgayNop;
    private javax.swing.JLabel labelThuocDien;
    private javax.swing.JLabel labelTrieuChung;
    private javax.swing.JRadioButton rdF0;
    private javax.swing.JRadioButton rdF1;
    private javax.swing.JRadioButton rdKhac;
    private javax.swing.JLabel tMaDon;
    private javax.swing.JLabel tMaGV;
    private javax.swing.JLabel tName;
    private javax.swing.JLabel tNameUniversity;
    private javax.swing.JTable tableKBYT;
    private javax.swing.JTextField txtKhac;
    private javax.swing.JTextField txtMaDon;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtNgayNop;
    // End of variables declaration//GEN-END:variables
}
