/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DangNhapPG.TaiKhoan;
import ObjectPG.DonXinNghi;
import ObjectPG.DonXinNghiSV;
import ObjectPG.SinhVien;
import ObjectPG.TableDonXinNghiSV;
import ObjectPG.TableQLSinhVien;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.TreeSet;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hello
 */
public class QuanLyDonXinNghiHocSinh extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyDonXinNghiHocSinh
     */
    int selectedIndex = -1;
    DonXinNghiSV d = new DonXinNghiSV();
    private String maSV;

    public QuanLyDonXinNghiHocSinh() {
        initComponents();
        DonXinNghiSV.readData();
        ButtonGroup b = new ButtonGroup();
        b.add(radio1);
        b.add(radio2);
        fillTable();
    }

    private void fillTable() {
        tblquanly.setModel(new TableDonXinNghiSV(DonXinNghiSV.dxnsvs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblquanly = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtMaSV = new javax.swing.JTextField();
        txtLyDo = new javax.swing.JTextField();
        txtAnh = new javax.swing.JTextField();
        txtTTSuckhoe = new javax.swing.JTextField();
        txtNgayNop = new javax.swing.JTextField();
        txtngayBD = new javax.swing.JTextField();
        txtNgayKetThuc = new javax.swing.JTextField();
        showAnh = new javax.swing.JLabel();
        btnduyet = new javax.swing.JButton();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quản Lý Đơn Xin Nghỉ");

        tblquanly.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblquanly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblquanlyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblquanly);

        jLabel2.setText("Mã đơn");

        jLabel3.setText("Mã SV");

        jLabel4.setText("Lý do");

        jLabel5.setText("Ảnh");

        jLabel6.setText("TTSK");

        jLabel7.setText("Ngày Nộp");

        jLabel8.setText("Ngày bắt đầu");

        jLabel9.setText("Ngày kết thúc");

        jLabel10.setText("Trạng thái");

        txtMa.setEnabled(false);

        txtMaSV.setEnabled(false);

        txtLyDo.setEnabled(false);

        txtAnh.setEnabled(false);

        txtTTSuckhoe.setEnabled(false);

        txtNgayNop.setEnabled(false);

        txtngayBD.setEnabled(false);

        txtNgayKetThuc.setEnabled(false);

        showAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnduyet.setText("Duyệt Đơn");
        btnduyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnduyetActionPerformed(evt);
            }
        });

        radio1.setText("Duyệt");

        radio2.setText("Không duyệt");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayNop, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTTSuckhoe, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(radio1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radio2)))
                .addGap(18, 18, 18)
                .addComponent(showAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnduyet, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTTSuckhoe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtNgayNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtngayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(radio1)
                                        .addComponent(radio2)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnduyet)
                    .addComponent(btnXoa))
                .addContainerGap(346, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblquanlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblquanlyMouseClicked
        // TODO add your handling code here:
        selectedIndex = tblquanly.getSelectedRow();
        if (selectedIndex != -1) {
            ArrayList<DonXinNghiSV> dxn = new ArrayList<DonXinNghiSV>(DonXinNghiSV.dxnsvs);
            d = dxn.get(selectedIndex);
            txtMa.setText(d.getMaDon());
            txtMaSV.setText(d.getMaSV());
            txtLyDo.setText(d.getLyDo());
            txtngayBD.setText(d.getNgayBatDauNghi());
            txtNgayKetThuc.setText(d.getNgayKetThucNghi());
            txtAnh.setText(d.getAnh());
            txtNgayNop.setText(d.getNgayNop());
            txtTTSuckhoe.setText(d.gettTSK());
            if (d.isTtDon()) {
                radio1.setSelected(true);
            } else {
                radio2.setSelected(true);
            }

            String link = d.getAnh().substring(d.getAnh().lastIndexOf("\\") + 1);
            try {
                BufferedImage img = null;
                img = ImageIO.read(new File("./src/File/Image/DonXinNghi/" + link));
                Image anh = img.getScaledInstance(showAnh.getWidth(), showAnh.getHeight(), Image.SCALE_SMOOTH);
                showAnh.setIcon(new ImageIcon(anh));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.toString());
            }
        }
    }//GEN-LAST:event_tblquanlyMouseClicked

    private void btnduyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnduyetActionPerformed
        // TODO add your handling code here:

        selectedIndex = tblquanly.getSelectedRow();
        if (selectedIndex != -1) {
            DonXinNghiSV temp = new DonXinNghiSV();
            ArrayList<DonXinNghiSV> tt = new ArrayList<DonXinNghiSV>(DonXinNghiSV.dxnsvs);
            temp = tt.get(selectedIndex);
            if (radio1.isSelected()) {
                temp.setTtDon(true);
            } else {
                temp.setTtDon(false);
            }
            tt.set(selectedIndex, temp);
            DonXinNghiSV.dxnsvs = new TreeSet<DonXinNghiSV>(tt);
            fillTable();
            DonXinNghiSV.writeData();
        }
    }//GEN-LAST:event_btnduyetActionPerformed
    private void Clear() {
        txtMa.setText("");
        txtMaSV.setText("");
        txtLyDo.setText("");
        txtAnh.setText("");
        txtNgayKetThuc.setText("");
        txtNgayNop.setText("");
        txtTTSuckhoe.setText("");
        txtngayBD.setText("");
        radio1.setSelected(false);
        radio2.setSelected(false);

    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        selectedIndex = tblquanly.getSelectedRow();
        if (selectedIndex != -1) {
            int select = JOptionPane.showConfirmDialog(this, "Xác nhận xóa ");
            if (select == 0) {
                ArrayList<DonXinNghiSV> ds = new ArrayList<DonXinNghiSV>(DonXinNghiSV.dxnsvs);
                DonXinNghiSV.dxnsvs.remove(ds.get(selectedIndex));
                fillTable();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                Clear();
                DonXinNghiSV.writeData();
            } else {
                JOptionPane.showMessageDialog(this, "chưa chọn dữ liệu");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnduyet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JLabel showAnh;
    private javax.swing.JTable tblquanly;
    private javax.swing.JTextField txtAnh;
    private javax.swing.JTextField txtLyDo;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtNgayKetThuc;
    private javax.swing.JTextField txtNgayNop;
    private javax.swing.JTextField txtTTSuckhoe;
    private javax.swing.JTextField txtngayBD;
    // End of variables declaration//GEN-END:variables
}
