/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ObjectPG.SinhVien;
import ObjectPG.TableQLSinhVien;
import ObjectPG.TableSapXepSV;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;

/**
 *
 * @author Hello
 */
public class SapXepSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form SapXepSinhVien
     */
    SinhVien sv = new SinhVien();
    ArrayList<SinhVien> a;

    public SapXepSinhVien() {
        initComponents();
        SinhVien.readData();
        cboSapXep.setSelectedIndex(-1);
        a = new ArrayList<SinhVien>(SinhVien.svs);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        fillTable();
    }

    public void fillTable() {
        tblSapXep.setModel(new TableSapXepSV(a));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSapXep = new javax.swing.JTable();
        cboSapXep = new javax.swing.JComboBox<>();
        btlSapXep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSapXep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSapXep);

        cboSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp xếp theo tên", "sắp xếp theo tình trạng sức khỏe", "sắp xếp theo khoa" }));

        btlSapXep.setText("Sắp Xếp");
        btlSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btlSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btlSapXep))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlSapXepActionPerformed
        // TODO add your handling code here:
        if (cboSapXep.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn dòng để sắp xếp");
        } else if (cboSapXep.getSelectedIndex() == 0) {
            Comparator<SinhVien> c = new Comparator<SinhVien>() {
                @Override
                public int compare(SinhVien t1, SinhVien t2) {
                    return t1.getHoTen().compareTo(t2.getHoTen());
                }
            };
            Collections.sort(a, c);
            fillTable();
        } else if (cboSapXep.getSelectedIndex() == 1) {
            Comparator<SinhVien> c = new Comparator<SinhVien>() {
                @Override
                public int compare(SinhVien t1, SinhVien t2) {
                    return t1.getTtsk().compareTo(t2.getTtsk());
                }
            };
            Collections.sort(a, c);
            fillTable();
        }
        else if(cboSapXep.getSelectedIndex()==2)
        {
            Comparator<SinhVien> c = new Comparator<SinhVien>() {
                @Override
                public int compare(SinhVien t1, SinhVien t2) {
                    return t1.getKhoa().compareTo(t2.getKhoa());
                }
            };
            Collections.sort(a, c);
            fillTable();
        }
    }//GEN-LAST:event_btlSapXepActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlSapXep;
    private javax.swing.JComboBox<String> cboSapXep;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSapXep;
    // End of variables declaration//GEN-END:variables
}
